require 'rubygems'
require 'rake'
require 'rake/testtask'
require 'rake/packagetask'
require 'rubygems/package_task'
require 'rspec/core/rake_task'
require 'gesmew/testing_support/common_rake'
load 'lib/tasks/exchanges.rake'

Bundler::GemHelper.install_tasks
RSpec::Core::RakeTask.new

spec = eval(File.read('gesmew_core.gemspec'))
Gem::PackageTask.new(spec) do |p|
  p.gem_spec = spec
end

desc "Release to gemcutter"
task :release do
  version = File.read(File.expand_path("../../GESMEW_VERSION", __FILE__)).strip
  cmd = "cd pkg && gem push gesmew_core-#{version}.gem"; puts cmd; system cmd
end

task :default => :spec

desc "Generates a dummy app for testing"
task :test_app do
  ENV['LIB_NAME'] = 'gesmew/core'
  Rake::Task['common:test_app'].invoke
end

task :stats => "omakase:stats"

